name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # Check out the repository
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Use Python 3.9
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install flake8  # Install Flake8 for linting
      - name: Lint with flake8
        run: |
          flake8 .  # Run Flake8 to lint the code

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # Check out the repository
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Use Python 3.9
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt  # Install project dependencies
          pip install pytest  # Install pytest for testing
      - name: Run tests
        run: |
          pytest  # Run the tests

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, test]  # Ensure linting and testing pass before deployment
    steps:
      - uses: actions/checkout@v2  # Check out the repository
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Use Python 3.9
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt  # Install project dependencies
      - name: Deploy model
        run: |
          python3 app.py  # Run the Flask app (for demonstration purposes)